#!/bin/python3

import base64
from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes
from Crypto.Util.Padding import pad, unpad

def input_b64():
  try:
    prefix = input("plaintext prefix (b64): ")
  except (KeyboardInterrupt, EOFError):
    print()
    exit(0)
  try:
    return base64.b64decode(prefix)
  except base64.binascii.Error:
    print(f"Error decoding base64 input: {prefix}")
    exit(1)

def main():
  key = get_random_bytes(16)
  cipher = AES.new(key=key, mode=AES.MODE_ECB)
  secret = b"Thisisasupersecretmessagethatisnotsupersecretatall..."
  ciphertext = cipher.encrypt(pad(secret, cipher.block_size))
  print("ciphertext (b64): " + base64.b64encode(ciphertext).decode())

  while True:
    plaintext_prefix = input_b64()
    ciphertext = cipher.encrypt(pad(plaintext_prefix + secret, cipher.block_size))
    print("ciphertext (b64): " + base64.b64encode(ciphertext).decode())

main()
